name: BunBridge
version: ${project.version}
main: github.vanes430.bunbridge.spigot.BunBridgeSpigot
api-version: 1.13
folia-supported: true
author: vanes430
commands:
  bun:
    description: Execute bun commands
    usage: /bun <args>
    permission: bunbridge.admin
  bunsetup:
    description: Install/Update Bun binary
    usage: /bunsetup
    permission: bunbridge.admin
